apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: rhods-nbc
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      overlays:
      - additional
      parameters:
      - name: odh-minimal-notebook-image-n
        value: ${RELATED_IMAGE_ODH_MINIMAL_NOTEBOOK_IMAGE_N}
      - name: odh-minimal-notebook-image-n-1
        value: ${RELATED_IMAGE_ODH_MINIMAL_NOTEBOOK_IMAGE_N_1}
      - name: odh-minimal-gpu-notebook-image-n
        value: ${RELATED_IMAGE_ODH_MINIMAL_GPU_NOTEBOOK_IMAGE_N}
      - name: odh-minimal-gpu-notebook-image-n-1
        value: ${RELATED_IMAGE_ODH_MINIMAL_GPU_NOTEBOOK_IMAGE_N_1}
      - name: odh-pytorch-gpu-notebook-image-n
        value: ${RELATED_IMAGE_ODH_PYTORCH_GPU_NOTEBOOK_IMAGE_N}
      - name: odh-pytorch-gpu-notebook-image-n-1
        value: ${RELATED_IMAGE_ODH_PYTORCH_GPU_NOTEBOOK_IMAGE_N_1}
      - name: odh-generic-data-science-notebook-image-n
        value:  ${RELATED_IMAGE_ODH_GENERIC_DATA_SCIENCE_NOTEBOOK_IMAGE_N}
      - name: odh-generic-data-science-notebook-image-n-1
        value:  ${RELATED_IMAGE_ODH_GENERIC_DATA_SCIENCE_NOTEBOOK_IMAGE_N_1}
      - name: odh-tensorflow-gpu-notebook-image-n
        value: ${RELATED_IMAGE_ODH_TENSORFLOW_GPU_NOTEBOOK_IMAGE_N}
      - name: odh-tensorflow-gpu-notebook-image-n-1
        value: ${RELATED_IMAGE_ODH_TENSORFLOW_GPU_NOTEBOOK_IMAGE_N_1}
      - name: odh-trustyai-notebook-image-n
        value: ${RELATED_IMAGE_ODH_TRUSTYAI_NOTEBOOK_IMAGE_N}
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  - kustomizeConfig:
      parameters:
      - name: odh-notebook-controller-image
        value: ${RELATED_IMAGE_ODH_NOTEBOOK_CONTROLLER_IMAGE}
      - name: odh-kf-notebook-controller-image
        value: ${RELATED_IMAGE_ODH_KF_NOTEBOOK_CONTROLLER_IMAGE}
      repoRef:
        name: manifests
        path: odh-notebook-controller
    name: odh-notebook-controller
  repos:
  - name: manifests
    uri: file:///opt/manifests/odh-manifests.tar.gz
  version: v1.0.0
